In [1]:
from google.colab import drive

drive.mount('/content/drive')
%cd drive
%cd MyDrive
%cd ML_Practicals

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive
/content/drive/MyDrive
/content/drive/MyDrive/ML_Practicals


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.io import arff

%matplotlib inline

In [3]:
data = arff.loadarff('credit-g.arff')
df = pd.DataFrame(data[0])
df

checking_status  duration                     credit_history  \
0             b'<0'       6.0  b'critical/other existing credit'   
1       b'0<=X<200'      48.0                   b'existing paid'   
2    b'no checking'      12.0  b'critical/other existing credit'   
3             b'<0'      42.0                   b'existing paid'   
4             b'<0'      24.0              b'delayed previously'   
..              ...       ...                                ...   
995  b'no checking'      12.0                   b'existing paid'   
996           b'<0'      30.0                   b'existing paid'   
997  b'no checking'      12.0                   b'existing paid'   
998           b'<0'      45.0                   b'existing paid'   
999     b'0<=X<200'      45.0  b'critical/other existing credit'   

                    purpose  credit_amount       savings_status  \
0               b'radio/tv'         1169.0  b'no known savings'   
1               b'radio/tv'         5951.0              b'<100'   
2              b'education'         2096.0              b'<100'   
3    b'furniture/equipment'         7882.0              b'<100'   
4                b'new car'         4870.0              b'<100'   
..                      ...            ...                  ...   
995  b'furniture/equipment'         1736.0              b'<100'   
996             b'used car'         3857.0              b'<100'   
997             b'radio/tv'          804.0              b'<100'   
998             b'radio/tv'         1845.0              b'<100'   
999             b'used car'         4576.0        b'100<=X<500'   

        employment  installment_commitment        personal_status  \
0           b'>=7'                     4.0         b'male single'   
1        b'1<=X<4'                     2.0  b'female div/dep/mar'   
2        b'4<=X<7'                     2.0         b'male single'   
3        b'4<=X<7'                     2.0         b'male single'   
4        b'1<=X<4'                     3.0         b'male single'   
..             ...                     ...                    ...   
995      b'4<=X<7'                     3.0  b'female div/dep/mar'   
996      b'1<=X<4'                     4.0        b'male div/sep'   
997         b'>=7'                     4.0         b'male single'   
998      b'1<=X<4'                     4.0         b'male single'   
999  b'unemployed'                     3.0         b'male single'   

    other_parties  ...    property_magnitude   age  other_payment_plans  \
0         b'none'  ...        b'real estate'  67.0              b'none'   
1         b'none'  ...        b'real estate'  22.0              b'none'   
2         b'none'  ...        b'real estate'  49.0              b'none'   
3    b'guarantor'  ...     b'life insurance'  45.0              b'none'   
4         b'none'  ...  b'no known property'  53.0              b'none'   
..            ...  ...                   ...   ...                  ...   
995       b'none'  ...        b'real estate'  31.0              b'none'   
996       b'none'  ...     b'life insurance'  40.0              b'none'   
997       b'none'  ...                b'car'  38.0              b'none'   
998       b'none'  ...  b'no known property'  23.0              b'none'   
999       b'none'  ...                b'car'  27.0              b'none'   

         housing existing_credits                           job  \
0         b'own'              2.0                    b'skilled'   
1         b'own'              1.0                    b'skilled'   
2         b'own'              1.0         b'unskilled resident'   
3    b'for free'              1.0                    b'skilled'   
4    b'for free'              2.0                    b'skilled'   
..           ...              ...                           ...   
995       b'own'              1.0         b'unskilled resident'   
996       b'own'              1.0  b'high qualif/self emp/mgmt'   
997       b'own'              1.0                

In [4]:
df.replace(to_replace='?', value=np.NaN)
df

checking_status  duration                     credit_history  \
0             b'<0'       6.0  b'critical/other existing credit'   
1       b'0<=X<200'      48.0                   b'existing paid'   
2    b'no checking'      12.0  b'critical/other existing credit'   
3             b'<0'      42.0                   b'existing paid'   
4             b'<0'      24.0              b'delayed previously'   
..              ...       ...                                ...   
995  b'no checking'      12.0                   b'existing paid'   
996           b'<0'      30.0                   b'existing paid'   
997  b'no checking'      12.0                   b'existing paid'   
998           b'<0'      45.0                   b'existing paid'   
999     b'0<=X<200'      45.0  b'critical/other existing credit'   

                    purpose  credit_amount       savings_status  \
0               b'radio/tv'         1169.0  b'no known savings'   
1               b'radio/tv'         5951.0              b'<100'   
2              b'education'         2096.0              b'<100'   
3    b'furniture/equipment'         7882.0              b'<100'   
4                b'new car'         4870.0              b'<100'   
..                      ...            ...                  ...   
995  b'furniture/equipment'         1736.0              b'<100'   
996             b'used car'         3857.0              b'<100'   
997             b'radio/tv'          804.0              b'<100'   
998             b'radio/tv'         1845.0              b'<100'   
999             b'used car'         4576.0        b'100<=X<500'   

        employment  installment_commitment        personal_status  \
0           b'>=7'                     4.0         b'male single'   
1        b'1<=X<4'                     2.0  b'female div/dep/mar'   
2        b'4<=X<7'                     2.0         b'male single'   
3        b'4<=X<7'                     2.0         b'male single'   
4        b'1<=X<4'                     3.0         b'male single'   
..             ...                     ...                    ...   
995      b'4<=X<7'                     3.0  b'female div/dep/mar'   
996      b'1<=X<4'                     4.0        b'male div/sep'   
997         b'>=7'                     4.0         b'male single'   
998      b'1<=X<4'                     4.0         b'male single'   
999  b'unemployed'                     3.0         b'male single'   

    other_parties  ...    property_magnitude   age  other_payment_plans  \
0         b'none'  ...        b'real estate'  67.0              b'none'   
1         b'none'  ...        b'real estate'  22.0              b'none'   
2         b'none'  ...        b'real estate'  49.0              b'none'   
3    b'guarantor'  ...     b'life insurance'  45.0              b'none'   
4         b'none'  ...  b'no known property'  53.0              b'none'   
..            ...  ...                   ...   ...                  ...   
995       b'none'  ...        b'real estate'  31.0              b'none'   
996       b'none'  ...     b'life insurance'  40.0              b'none'   
997       b'none'  ...                b'car'  38.0              b'none'   
998       b'none'  ...  b'no known property'  23.0              b'none'   
999       b'none'  ...                b'car'  27.0              b'none'   

         housing existing_credits                           job  \
0         b'own'              2.0                    b'skilled'   
1         b'own'              1.0                    b'skilled'   
2         b'own'              1.0         b'unskilled resident'   
3    b'for free'              1.0                    b'skilled'   
4    b'for free'              2.0                    b'skilled'   
..           ...              ...                           ...   
995       b'own'              1.0         b'unskilled resident'   
996       b'own'              1.0  b'high qualif/self emp/mgmt'   
997       b'own'              1.0                

In [5]:
df.isnull().sum()

checking_status           0
duration                  0
credit_history            0
purpose                   0
credit_amount             0
savings_status            0
employment                0
installment_commitment    0
personal_status           0
other_parties             0
residence_since           0
property_magnitude        0
age                       0
other_payment_plans       0
housing                   0
existing_credits          0
job                       0
num_dependents            0
own_telephone             0
foreign_worker            0
class                     0
dtype: int64

In [6]:
x = df.iloc[:, 1:]
x

duration                     credit_history                 purpose  \
0         6.0  b'critical/other existing credit'             b'radio/tv'   
1        48.0                   b'existing paid'             b'radio/tv'   
2        12.0  b'critical/other existing credit'            b'education'   
3        42.0                   b'existing paid'  b'furniture/equipment'   
4        24.0              b'delayed previously'              b'new car'   
..        ...                                ...                     ...   
995      12.0                   b'existing paid'  b'furniture/equipment'   
996      30.0                   b'existing paid'             b'used car'   
997      12.0                   b'existing paid'             b'radio/tv'   
998      45.0                   b'existing paid'             b'radio/tv'   
999      45.0  b'critical/other existing credit'             b'used car'   

     credit_amount       savings_status     employment  \
0           1169.0  b'no known savings'         b'>=7'   
1           5951.0              b'<100'      b'1<=X<4'   
2           2096.0              b'<100'      b'4<=X<7'   
3           7882.0              b'<100'      b'4<=X<7'   
4           4870.0              b'<100'      b'1<=X<4'   
..             ...                  ...            ...   
995         1736.0              b'<100'      b'4<=X<7'   
996         3857.0              b'<100'      b'1<=X<4'   
997          804.0              b'<100'         b'>=7'   
998         1845.0              b'<100'      b'1<=X<4'   
999         4576.0        b'100<=X<500'  b'unemployed'   

     installment_commitment        personal_status other_parties  \
0                       4.0         b'male single'       b'none'   
1                       2.0  b'female div/dep/mar'       b'none'   
2                       2.0         b'male single'       b'none'   
3                       2.0         b'male single'  b'guarantor'   
4                       3.0         b'male single'       b'none'   
..                      ...                    ...           ...   
995                     3.0  b'female div/dep/mar'       b'none'   
996                     4.0        b'male div/sep'       b'none'   
997                     4.0         b'male single'       b'none'   
998                     4.0         b'male single'       b'none'   
999                     3.0         b'male single'       b'none'   

     residence_since    property_magnitude   age other_payment_plans  \
0                4.0        b'real estate'  67.0             b'none'   
1                2.0        b'real estate'  22.0             b'none'   
2                3.0        b'real estate'  49.0             b'none'   
3                4.0     b'life insurance'  45.0             b'none'   
4                4.0  b'no known property'  53.0             b'none'   
..               ...                   ...   ...                 ...   
995              4.0        b'real estate'  31.0             b'none'   
996              4.0     b'life insurance'  40.0             b'none'   
997              4.0                b'car'  38.0             b'none'   
998              4.0  b'no known property'  23.0             b'none'   
999              4.0                b'car'  27.0             b'none'   

         housing  existing_credits                           job  \
0         b'own'               2.0                    b'skilled'   
1         b'own'               1.0                    b'skilled'   
2         b'own'               1.0         b'unskilled resident'   
3    b'for free'               1.0                    b'skilled'   
4    b'for free'               2.0                    b'skilled'   
..           ...               ...                           ...   
995       b'own'               1.0         b'unskilled resident'   
996       b'own'               1.0  b'high qualif/self emp/mgmt'   
997       b'own'               1.0                    b'skilled'   
998  b'for free'               1.

In [7]:
y = df.iloc[:, :1]
y

checking_status
0             b'<0'
1       b'0<=X<200'
2    b'no checking'
3             b'<0'
4             b'<0'
..              ...
995  b'no checking'
996           b'<0'
997  b'no checking'
998           b'<0'
999     b'0<=X<200'

[1000 rows x 1 columns]

In [8]:
from sklearn.preprocessing import LabelEncoder as le

for column in x.columns:
  if column == 'credit_amount':
    continue
  x[column] = le().fit_transform(x[column])

x

duration  credit_history  purpose  credit_amount  savings_status  \
0           2               1        6         1169.0               4   
1          29               3        6         5951.0               2   
2           8               1        2         2096.0               2   
3          26               3        3         7882.0               2   
4          17               2        4         4870.0               2   
..        ...             ...      ...            ...             ...   
995         8               3        3         1736.0               2   
996        21               3        9         3857.0               2   
997         8               3        6          804.0               2   
998        27               3        6         1845.0               2   
999        27               1        9         4576.0               0   

     employment  installment_commitment  personal_status  other_parties  \
0             3                       3                3              2   
1             0                       1                0              2   
2             1                       1                3              2   
3             1                       1                3              1   
4             0                       2                3              2   
..          ...                     ...              ...            ...   
995           1                       2                0              2   
996           0                       3                1              2   
997           3                       3                3              2   
998           0                       3                3              2   
999           4                       2                3              2   

     residence_since  property_magnitude  age  other_payment_plans  housing  \
0                  3                   3   48                    1        1   
1                  1                   3    3                    1        1   
2                  2                   3   30                    1        1   
3                  3                   1   26                    1        0   
4                  3                   2   34                    1        0   
..               ...                 ...  ...                  ...      ...   
995                3                   3   12                    1        1   
996                3                   1   21                    1        1   
997                3                   0   19                    1        1   
998                3                   2    4                    1        0   
999                3                   0    8                    1        1   

     existing_credits  job  num_dependents  own_telephone  foreign_worker  \
0                   1    1               0              1               1   
1                   0    1               0              0               1   
2                   0    3               1              0               1   
3                   0    1               1              0               1   
4                   1    1               1              0               1   
..                ...  ...             ...            ...             ...   
995                 0    3               0              0               1   
996                 0    0               0              1               1   
997                 0    1               0              0               1   
998                 0    1               0              1               1   
999                 0    1               0              0               1   

     class  
0        1  
1        0  
2        1  
3        1  
4        0  
..     ...  
995      1  
996      1  
997      1  
998      0  
999      1  

[1000 rows x 20 columns]

In [9]:
y['checking_status'] = le().fit_transform(y['checking_status'])
y

checking_status
0                  1
1                  0
2                  3
3                  1
4                  1
..               ...
995                3
996                1
997                3
998                1
999                0

[1000 rows x 1 columns]

In [10]:
y = y.to_numpy()
y

array([[1],
       [0],
       [3],
       [1],
       [1],
       [3],
       [3],
       [0],
       [3],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [3],
       [1],
       [0],
       [3],
       [3],
       [1],
       [1],
       [0],
       [3],
       [1],
       [3],
       [2],
       [0],
       [1],
       [0],
       [1],
       [0],
       [3],
       [2],
       [0],
       [3],
       [2],
       [2],
       [0],
       [3],
       [0],
       [0],
       [1],
       [1],
       [3],
       [3],
       [1],
       [3],
       [3],
       [0],
       [0],
       [3],
       [3],
       [0],
       [3],
       [0],
       [3],
       [2],
       [1],
       [0],
       [0],
       [0],
       [0],
       [3],
       [3],
       [3],
       [0],
       [3],
       [3],
       [3],
       [3],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [3],
       [0],
       [3],
       [3],
       [3],
    

In [11]:
from sklearn.preprocessing import OneHotEncoder as oe

x = oe().fit_transform(x).toarray()
x

array([[0., 0., 1., ..., 1., 0., 1.],
       [0., 0., 0., ..., 1., 1., 0.],
       [0., 0., 0., ..., 1., 0., 1.],
       ...,
       [0., 0., 0., ..., 1., 0., 1.],
       [0., 0., 0., ..., 1., 1., 0.],
       [0., 0., 0., ..., 1., 0., 1.]])

In [12]:
x.shape

(1000, 1073)

In [13]:
y.shape

(1000, 1)

In [14]:
from sklearn.model_selection import train_test_split as test

x_train, x_test, y_train, y_test = test(x, y, test_size=0.10, random_state=10)

print('X_train : ', x_train)
print('X_test : ', x_test)
print('Y_train : ', y_train)
print('Y_test : ', y_test)

X_train :  [[0. 0. 0. ... 1. 0. 1.]
 [0. 0. 0. ... 1. 0. 1.]
 [0. 0. 0. ... 1. 0. 1.]
 ...
 [0. 0. 0. ... 1. 0. 1.]
 [0. 0. 0. ... 1. 0. 1.]
 [0. 0. 0. ... 1. 1. 0.]]
X_test :  [[0. 0. 0. ... 1. 0. 1.]
 [0. 0. 0. ... 1. 0. 1.]
 [0. 0. 0. ... 1. 0. 1.]
 ...
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 1. 1. 0.]]
Y_train :  [[1]
 [0]
 [0]
 [3]
 [3]
 [3]
 [0]
 [3]
 [3]
 [1]
 [3]
 [3]
 [1]
 [0]
 [0]
 [3]
 [1]
 [3]
 [1]
 [1]
 [3]
 [3]
 [2]
 [1]
 [3]
 [3]
 [3]
 [0]
 [0]
 [3]
 [0]
 [0]
 [1]
 [0]
 [1]
 [3]
 [1]
 [3]
 [3]
 [3]
 [0]
 [3]
 [1]
 [3]
 [3]
 [3]
 [1]
 [3]
 [0]
 [3]
 [1]
 [1]
 [2]
 [1]
 [0]
 [3]
 [1]
 [0]
 [3]
 [3]
 [1]
 [3]
 [0]
 [3]
 [3]
 [0]
 [0]
 [0]
 [3]
 [1]
 [2]
 [3]
 [1]
 [2]
 [0]
 [3]
 [0]
 [1]
 [0]
 [3]
 [1]
 [0]
 [0]
 [0]
 [1]
 [3]
 [1]
 [0]
 [0]
 [3]
 [3]
 [3]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [3]
 [3]
 [1]
 [0]
 [3]
 [0]
 [3]
 [3]
 [1]
 [3]
 [0]
 [0]
 [0]
 [0]
 [3]
 [1]
 [3]
 [1]
 [0]
 [0]
 [1]
 [0]
 [3]
 [0]
 [0]
 [3]
 [1]
 [1]
 [3]
 [3]
 [3]
 [1]
 [0]
 

In [15]:
print('X : ', x.shape)
print('Y : ', y.shape)
print('X_train : ', x_train.shape)
print('X_test : ', x_test.shape)
print('Y_train : ', y_train.shape)
print('Y_test : ', y_test.shape)

X :  (1000, 1073)
Y :  (1000, 1)
X_train :  (900, 1073)
X_test :  (100, 1073)
Y_train :  (900, 1)
Y_test :  (100, 1)


In [16]:
y_train = y_train.ravel()
y_test = y_test.ravel()

y_train

array([1, 0, 0, 3, 3, 3, 0, 3, 3, 1, 3, 3, 1, 0, 0, 3, 1, 3, 1, 1, 3, 3,
       2, 1, 3, 3, 3, 0, 0, 3, 0, 0, 1, 0, 1, 3, 1, 3, 3, 3, 0, 3, 1, 3,
       3, 3, 1, 3, 0, 3, 1, 1, 2, 1, 0, 3, 1, 0, 3, 3, 1, 3, 0, 3, 3, 0,
       0, 0, 3, 1, 2, 3, 1, 2, 0, 3, 0, 1, 0, 3, 1, 0, 0, 0, 1, 3, 1, 0,
       0, 3, 3, 3, 0, 0, 1, 1, 0, 0, 3, 3, 1, 0, 3, 0, 3, 3, 1, 3, 0, 0,
       0, 0, 3, 1, 3, 1, 0, 0, 1, 0, 3, 0, 0, 3, 1, 1, 3, 3, 3, 1, 0, 1,
       1, 2, 0, 0, 1, 3, 3, 0, 3, 3, 0, 3, 3, 3, 2, 0, 3, 0, 0, 3, 3, 3,
       1, 3, 2, 3, 1, 1, 1, 1, 3, 3, 2, 3, 1, 3, 0, 3, 0, 3, 1, 2, 3, 3,
       3, 3, 3, 1, 1, 1, 0, 1, 1, 1, 1, 3, 3, 3, 0, 1, 3, 0, 0, 3, 1, 2,
       1, 1, 3, 3, 3, 0, 3, 3, 0, 1, 3, 0, 1, 1, 3, 1, 3, 1, 3, 0, 0, 3,
       3, 1, 0, 0, 0, 3, 3, 0, 0, 1, 3, 3, 2, 3, 1, 3, 0, 1, 3, 1, 3, 0,
       1, 3, 0, 0, 0, 1, 1, 1, 3, 3, 3, 3, 3, 0, 1, 3, 3, 2, 3, 1, 3, 2,
       3, 1, 3, 0, 2, 0, 1, 0, 3, 3, 0, 3, 3, 3, 3, 0, 3, 3, 1, 3, 2, 1,
       1, 3, 2, 0, 0, 3, 1, 0, 3, 3, 3, 3, 1, 0, 3,

In [17]:
from sklearn.linear_model import LogisticRegression as lr

logist = lr(penalty='l2', solver='lbfgs', max_iter=1000, verbose=1)
model = logist.fit(x_train, y_train)
predictions = logist.predict(x_test)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    1.5s finished


In [18]:
from sklearn.metrics import confusion_matrix as cm
from sklearn.metrics import accuracy_score as acs
from sklearn.metrics import classification_report as cr

print('Confusion Matrix :\n', cm(y_test, predictions))
print('\nAccuracy Score : ', acs(y_test, predictions))
print('\nReport :\n', cr(y_test, predictions))

Confusion Matrix :
 [[10  5  1  7]
 [ 6 14  0 10]
 [ 3  0  0  9]
 [ 4  5  0 26]]

Accuracy Score :  0.5

Report :
               precision    recall  f1-score   support

           0       0.43      0.43      0.43        23
           1       0.58      0.47      0.52        30
           2       0.00      0.00      0.00        12
           3       0.50      0.74      0.60        35

    accuracy                           0.50       100
   macro avg       0.38      0.41      0.39       100
weighted avg       0.45      0.50      0.46       100

