In [1]:
from google.colab import drive

drive.mount('/content/drive')
%cd drive
%cd MyDrive
%cd ML_Practicals

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive
/content/drive/MyDrive
/content/drive/MyDrive/ML_Practicals


## KNN Classifier

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split as test
from sklearn.preprocessing import StandardScaler as sc
from sklearn.metrics import confusion_matrix as cm
from sklearn.metrics import classification_report as cr
from sklearn.neighbors import KNeighborsClassifier

%matplotlib inline

In [3]:
df = pd.read_csv('Prototask.data', sep=' ')
df

lread  lwrite  scall  sread  swrite   fork   exec   rchar   wchar  \
0         6       2   1036    103     114   1.00   1.00  172076  355965   
1         1       0   2165    205     101   0.40   1.20   43107   44139   
2        62      77   3806    258     166   1.40   1.40  492142  268706   
3         5       0   4721    256     177   0.99   2.58  524787  174964   
4        42      55   3949    249     244   2.60   4.60  197289  529200   
...     ...     ...    ...    ...     ...    ...    ...     ...     ...   
8187     74      49   2688    176     103  11.00  32.20   57714   38484   
8188     29      40   1906    118      90   0.80   2.00    8175   27313   
8189      3       0    926     90      67   0.60   1.00    5411   19322   
8190      4       0    418     30      29   0.80   1.00    3959   10679   
8191      5       0   1888    248     215   6.20   1.80  216420   39346   

      runqsz  freemem  freeswap  usr  
0        2.0     6527   1851864   90  
1        3.0      130   1131931   88  
2        5.2      256   1314590   85  
3        1.0      233    972606   81  
4        3.4      331   1013805   79  
...      ...      ...       ...  ...  
8187     7.0      314   1096333   69  
8188     3.6      166   1107088   88  
8189     1.0     1177   1020400   92  
8190     2.4     6355   1702592   96  
8191     4.6     1628   1757696   80  

[8192 rows x 13 columns]

In [4]:
x = df.iloc[:, :-1]
y = df.iloc[:, -1:]

In [5]:
x

lread  lwrite  scall  sread  swrite   fork   exec   rchar   wchar  \
0         6       2   1036    103     114   1.00   1.00  172076  355965   
1         1       0   2165    205     101   0.40   1.20   43107   44139   
2        62      77   3806    258     166   1.40   1.40  492142  268706   
3         5       0   4721    256     177   0.99   2.58  524787  174964   
4        42      55   3949    249     244   2.60   4.60  197289  529200   
...     ...     ...    ...    ...     ...    ...    ...     ...     ...   
8187     74      49   2688    176     103  11.00  32.20   57714   38484   
8188     29      40   1906    118      90   0.80   2.00    8175   27313   
8189      3       0    926     90      67   0.60   1.00    5411   19322   
8190      4       0    418     30      29   0.80   1.00    3959   10679   
8191      5       0   1888    248     215   6.20   1.80  216420   39346   

      runqsz  freemem  freeswap  
0        2.0     6527   1851864  
1        3.0      130   1131931  
2        5.2      256   1314590  
3        1.0      233    972606  
4        3.4      331   1013805  
...      ...      ...       ...  
8187     7.0      314   1096333  
8188     3.6      166   1107088  
8189     1.0     1177   1020400  
8190     2.4     6355   1702592  
8191     4.6     1628   1757696  

[8192 rows x 12 columns]

In [6]:
y

usr
0      90
1      88
2      85
3      81
4      79
...   ...
8187   69
8188   88
8189   92
8190   96
8191   80

[8192 rows x 1 columns]

In [7]:
x_train, x_test, y_train, y_test = test(x, y, test_size=0.20)

In [8]:
scaler = sc()
scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [9]:
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [10]:
y_predicted = classifier.predict(x_test)

print('Confusion Matrix :\n', cm(y_test, y_predicted))
print('\nClassification Report :\n', cr(y_test, y_predicted))

Confusion Matrix :
 [[55  0  0 ...  0  0  0]
 [ 3  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ... 25 17  0]
 [ 0  0  0 ... 19 38  2]
 [ 0  0  0 ...  1 12  0]]

Classification Report :
               precision    recall  f1-score   support

           0       0.95      1.00      0.97        55
           1       0.00      0.00      0.00         4
          49       0.00      0.00      0.00         1
          50       0.00      0.00      0.00         1
          51       0.00      0.00      0.00         0
          52       0.00      0.00      0.00         1
          54       0.00      0.00      0.00         0
          55       0.00      0.00      0.00         2
          56       0.00      0.00      0.00         0
          57       0.00      0.00      0.00         1
          58       0.00      0.00      0.00         3
          59       0.00      0.00      0.00         3
          60       0.00      0.00      0.00         6
          61       0.00      0.00      0.

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1

## SVM Classifier

In [11]:
from sklearn.svm import SVC

train_set, test_set = test(df, test_size=0.20, random_state=1)

X_train = train_set.iloc[:, :2].values
X_test = test_set.iloc[:, :2].values
Y_train = train_set.iloc[:, 2].values
Y_test = test_set.iloc[:, 2].values

svm_classifier = SVC(kernel='rbf', random_state=1)
svm_classifier.fit(X_train, Y_train)

SVC(random_state=1)

In [12]:
Y_predicted = svm_classifier.predict(X_test)

print('Confusion Matrix :\n', cm(Y_test, Y_predicted))
print('\nClassification Report :\n', cr(Y_test, Y_predicted))

Confusion Matrix :
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

Classification Report :
               precision    recall  f1-score   support

         128       0.00      0.00      0.00         1
         132       0.00      0.00      0.00         1
         139       0.00      0.00      0.00         1
         140       0.00      0.00      0.00         1
         142       0.00      0.00      0.00         1
         148       0.00      0.00      0.00         1
         149       0.00      0.00      0.00         1
         152       0.00      0.00      0.00         1
         155       0.00      0.00      0.00         1
         156       0.00      0.00      0.00         2
         157       0.00      0.00      0.00         1
         158       0.00      1.00      0.00         1
         159       0.00      0.00      0.00         1
         160       0.00      0.00      0.00         0
         161       0.00

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1

In [13]:
test_set['Predictions'] = Y_predicted

print('Accuracy : ', float(cm(Y_test, Y_predicted).diagonal().sum())/len(Y_test))

Accuracy :  0.0006101281269066504


## Naive Bayes Classifier

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8192 entries, 0 to 8191
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   lread     8192 non-null   int64  
 1   lwrite    8192 non-null   int64  
 2   scall     8192 non-null   int64  
 3   sread     8192 non-null   int64  
 4   swrite    8192 non-null   int64  
 5   fork      8192 non-null   float64
 6   exec      8192 non-null   float64
 7   rchar     8192 non-null   int64  
 8   wchar     8192 non-null   int64  
 9   runqsz    8192 non-null   float64
 10  freemem   8192 non-null   int64  
 11  freeswap  8192 non-null   int64  
 12  usr       8192 non-null   int64  
dtypes: float64(3), int64(10)
memory usage: 832.1 KB


In [15]:
categorical = [var for var in df.columns if df[var].dtype=='0']
categorical

[]

In [16]:
x_train, x_test, y_train, y_test = test(x, y, test_size=0.30, random_state=1)

x_train.shape, x_test.shape

((5734, 12), (2458, 12))

In [17]:
x_train.dtypes

lread         int64
lwrite        int64
scall         int64
sread         int64
swrite        int64
fork        float64
exec        float64
rchar         int64
wchar         int64
runqsz      float64
freemem       int64
freeswap      int64
dtype: object

In [18]:
x_train.isnull().sum()

lread       0
lwrite      0
scall       0
sread       0
swrite      0
fork        0
exec        0
rchar       0
wchar       0
runqsz      0
freemem     0
freeswap    0
dtype: int64

In [19]:
from sklearn.naive_bayes import GaussianNB

gnb_classifier = GaussianNB()
gnb_classifier.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [20]:
from sklearn.metrics import accuracy_score as acs

y_predicted = gnb_classifier.predict(x_test)

print('Accuracy : ', acs(y_test, y_predicted))

Accuracy :  0.15419039869812856


In [21]:
y_pred_train = gnb_classifier.predict(x_train)

print('Accuracy : ', acs(y_train, y_pred_train))

Accuracy :  0.15521450994070457


In [22]:
print('Training set score : ', gnb_classifier.score(x_train, y_train))
print('Test set score : ', gnb_classifier.score(x_test, y_test))

Training set score :  0.15521450994070457
Test set score :  0.15419039869812856


In [23]:
print('Confusion Matrix :\n', cm(y_test, y_predicted))

print('True Positives : ', cm(y_test, y_predicted)[1,1])
print('True Negatives : ', cm(y_test, y_predicted)[0,0])
print('False Positives : ', cm(y_test, y_predicted)[0,1])
print('False Negatives : ', cm(y_test, y_predicted)[1,0])

Confusion Matrix :
 [[93  5  0 ...  0  0  0]
 [ 4  0  0 ...  0  0  0]
 [ 1  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ... 23 52 20]
 [ 0  0  0 ...  6 45 54]
 [ 0  0  0 ...  0  6 13]]
True Positives :  0
True Negatives :  93
False Positives :  5
False Negatives :  4


In [24]:
print('Classification Report :\n', cr(y_test, y_predicted))

Classification Report :
               precision    recall  f1-score   support

           0       0.95      0.95      0.95        98
           1       0.00      0.00      0.00         4
           2       0.00      0.00      0.00         1
          50       0.00      0.00      0.00         2
          51       0.00      0.00      0.00         1
          52       0.00      0.00      0.00         0
          53       0.00      0.00      0.00         1
          54       0.00      0.00      0.00         3
          55       0.00      0.00      0.00         4
          56       0.00      0.00      0.00         5
          57       0.00      0.00      0.00         2
          58       0.00      0.00      0.00         5
          59       0.00      0.00      0.00         7
          60       0.00      0.00      0.00         6
          61       0.00      0.00      0.00         8
          62       0.03      0.33      0.05         3
          63       0.00      0.00      0.00        10
  

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1