In [1]:
from google.colab import drive

drive.mount('/content/drive')
%cd drive
%cd MyDrive
%cd ML_Practicals

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive
/content/drive/MyDrive
/content/drive/MyDrive/ML_Practicals


## KNN Classifier

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split as test
from sklearn.preprocessing import StandardScaler as sc
from sklearn.metrics import confusion_matrix as cm
from sklearn.metrics import classification_report as cr
from sklearn.neighbors import KNeighborsClassifier

%matplotlib inline

In [3]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data',
                 names=['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class'])
df

sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
x = df.iloc[:, :-1]
y = df.iloc[:, -1:]

In [5]:
x

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [6]:
y

class
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 1 columns]

In [7]:
x_train, x_test, y_train, y_test = test(x, y, test_size=0.20)

In [8]:
scaler = sc()
scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [9]:
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [10]:
y_predicted = classifier.predict(x_test)

print('Confusion Matrix :\n', cm(y_test, y_predicted))
print('\nClassification Report :\n', cr(y_test, y_predicted))

Confusion Matrix :
 [[ 8  0  0]
 [ 0  7  1]
 [ 0  0 14]]

Classification Report :
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         8
Iris-versicolor       1.00      0.88      0.93         8
 Iris-virginica       0.93      1.00      0.97        14

       accuracy                           0.97        30
      macro avg       0.98      0.96      0.97        30
   weighted avg       0.97      0.97      0.97        30



## SVM Classifier

In [11]:
from sklearn.svm import SVC

train_set, test_set = test(df, test_size=0.20, random_state=1)

X_train = train_set.iloc[:, :-1].values
X_test = test_set.iloc[:, :-1].values
Y_train = train_set.iloc[:, -1].values
Y_test = test_set.iloc[:, -1].values

svm_classifier = SVC()
svm_classifier.fit(X_train, Y_train)

SVC()

In [12]:
Y_predicted = svm_classifier.predict(X_test)

print('Confusion Matrix :\n', cm(Y_test, Y_predicted))
print('\nClassification Report :\n', cr(Y_test, Y_predicted))

Confusion Matrix :
 [[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]

Classification Report :
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      0.92      0.96        13
 Iris-virginica       0.86      1.00      0.92         6

       accuracy                           0.97        30
      macro avg       0.95      0.97      0.96        30
   weighted avg       0.97      0.97      0.97        30



In [13]:
test_set['Predictions'] = Y_predicted

print('Accuracy : ', float(cm(Y_test, Y_predicted).diagonal().sum())/len(Y_test))

Accuracy :  0.9666666666666667


## Naive Bayes Classifier

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   class         150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [15]:
categorical = [var for var in df.columns if df[var].dtype=='0']
categorical

[]

In [16]:
x_train, x_test, y_train, y_test = test(x, y, test_size=0.30, random_state=1)

x_train.shape, x_test.shape

((105, 4), (45, 4))

In [17]:
x_train.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
dtype: object

In [18]:
x_train.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
dtype: int64

In [19]:
from sklearn.naive_bayes import GaussianNB

gnb_classifier = GaussianNB()
gnb_classifier.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [20]:
from sklearn.metrics import accuracy_score as acs

y_predicted = gnb_classifier.predict(x_test)

print('Accuracy : ', acs(y_test, y_predicted))

Accuracy :  0.9333333333333333


In [21]:
y_pred_train = gnb_classifier.predict(x_train)

print('Accuracy : ', acs(y_train, y_pred_train))

Accuracy :  0.9523809523809523


In [22]:
print('Training set score : ', gnb_classifier.score(x_train, y_train))
print('Test set score : ', gnb_classifier.score(x_test, y_test))

Training set score :  0.9523809523809523
Test set score :  0.9333333333333333


In [23]:
print('Confusion Matrix :\n', cm(y_test, y_predicted))

print('True Positives : ', cm(y_test, y_predicted)[1,1])
print('True Negatives : ', cm(y_test, y_predicted)[0,0])
print('False Positives : ', cm(y_test, y_predicted)[0,1])
print('False Negatives : ', cm(y_test, y_predicted)[1,0])

Confusion Matrix :
 [[14  0  0]
 [ 0 16  2]
 [ 0  1 12]]
True Positives :  16
True Negatives :  14
False Positives :  0
False Negatives :  0


In [24]:
print('Classification Report :\n', cr(y_test, y_predicted))

Classification Report :
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        14
Iris-versicolor       0.94      0.89      0.91        18
 Iris-virginica       0.86      0.92      0.89        13

       accuracy                           0.93        45
      macro avg       0.93      0.94      0.93        45
   weighted avg       0.94      0.93      0.93        45

