In [1]:
from google.colab import drive

drive.mount('/content/drive')
%cd drive
%cd MyDrive
%cd ML_Practicals

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive
/content/drive/MyDrive
/content/drive/MyDrive/ML_Practicals


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [3]:
# http://ftp.cs.toronto.edu/pub/neuron/delve/data/tarfiles/comp-activ.tar.gz
df = pd.read_csv('comp-activ.data', sep=' ', ).iloc[:, :27]
df

time  lread  lwrite  scall  sread  swrite  fork  exec    rchar  \
0     11:30:07     44       0   3700    410     200  3.39  5.79   544367   
1     15:44:35      7       0   3459    373     391  5.60  1.60   237571   
2     11:09:06      7       4   4627   1283     136  2.00  3.59   509700   
3     15:44:09      7       0   4197    627     498  5.59  2.00   274637   
4     14:00:10      3       1   4821    236     258  2.00  9.38    83870   
...        ...    ...     ...    ...    ...     ...   ...   ...      ...   
8187  22:51:24      2       1    888     52      59  0.20  0.20   237283   
8188  19:03:40     36      57    453     42      34  0.60  0.60    27437   
8189  13:04:34     24       7   5880   1236    1128  6.40  6.00  1301407   
8190  16:09:20     14       5   3690    183     134  0.60  0.60   152858   
8191  16:19:20     55      72   2012    153     120  0.80  2.40    26815   

       wchar  ...    pflt    vflt  runqsz  runocc  freemem  freeswap  usr  \
0     247202  ...  618.16  427.15     2.0      20      180   1118221   75   
1     409952  ...  268.00  417.20     2.2     100      178   1374995   79   
2      50768  ...  176.85  270.66     1.8     100      243   1130699   79   
3     141793  ...  280.24  496.81     1.8      80      161    980552   77   
4     479867  ...   74.45  163.87     2.0     100      963   1037206   80   
...      ...  ...     ...     ...     ...     ...      ...       ...  ...   
8187  288087  ...   13.97   23.35     2.0     100     4355   1818307   96   
8188   19314  ...  117.60   42.00     2.8     100     1019   1717410   95   
8189  888107  ...  296.80  512.80     1.0      20      721   1057133   66   
8190   33955  ...   52.20  121.80     3.2     100      687   1528750   89   
8191   27304  ...   58.80   57.00     2.2     100     1232    975296   89   

      sys  wio  idle  
0      25  0.0   0.0  
1      21  0.0   0.0  
2      21  0.0   0.0  
3      23  0.0   0.0  
4      19  0.0   0.0  
...   ...  ...   ...  
8187    4  0.0   0.0  
8188    5  0.0   0.0  
8189   34  0.0   0.0  
8190   11  0.0   0.0  
8191   11  0.0   0.0  

[8192 rows x 27 columns]

In [4]:
df.describe()

lread       lwrite         scall        sread       swrite  \
count  8192.000000  8192.000000   8192.000000  8192.000000  8192.000000   
mean     19.559692    13.106201   2306.318237   210.479980   150.058228   
std      53.353799    29.891726   1633.617322   198.980146   160.478980   
min       0.000000     0.000000    109.000000     6.000000     7.000000   
25%       2.000000     0.000000   1012.000000    86.000000    63.000000   
50%       7.000000     1.000000   2051.500000   166.000000   117.000000   
75%      20.000000    10.000000   3317.250000   279.000000   185.000000   
max    1845.000000   575.000000  12493.000000  5318.000000  5456.000000   

              fork         exec         rchar         wchar        pgout  ...  \
count  8192.000000  8192.000000  8.192000e+03  8.192000e+03  8192.000000  ...   
mean      1.884554     2.791998  1.970137e+05  9.589829e+04     2.285317  ...   
std       2.479493     5.212456  2.394808e+05  1.407569e+05     5.307038  ...   
min       0.000000     0.000000  2.780000e+02  1.498000e+03     0.000000  ...   
25%       0.400000     0.200000  3.386425e+04  2.293550e+04     0.000000  ...   
50%       0.800000     1.200000  1.247795e+05  4.662000e+04     0.000000  ...   
75%       2.200000     2.800000  2.676692e+05  1.061480e+05     2.400000  ...   
max      20.120000    59.560000  2.526649e+06  1.801623e+06    81.440000  ...   

              pflt         vflt       runqsz         runocc       freemem  \
count  8192.000000  8192.000000  8192.000000    8192.000000   8192.000000   
mean    109.793799   185.315796    19.630676   34083.708984   1763.456299   
std     114.419221   191.000603   125.742085  176240.759051   2482.104511   
min       0.000000     0.200000     1.000000      19.000000     55.000000   
25%      25.000000    45.400000     1.200000      80.000000    231.000000   
50%      63.800000   120.400000     2.000000     100.000000    579.000000   
75%     159.600000   251.800000     3.000000     100.000000   2002.250000   
max     899.800000  1365.000000  2823.000000  966378.000000  12027.000000   

           freeswap          usr          sys          wio         idle  
count  8.192000e+03  8192.000000  8192.000000  7898.000000  7898.000000  
mean   1.328126e+06    83.968872    12.390747     0.005698     0.040137  
std    4.220194e+05    18.401905     9.011396     0.078565     0.220593  
min    2.000000e+00     0.000000     0.000000     0.000000     0.000000  
25%    1.042624e+06    81.000000     6.000000     0.000000     0.000000  
50%    1.289290e+06    89.000000    10.000000     0.000000     0.000000  
75%    1.730380e+06    94.000000    17.000000     0.000000     0.000000  
max    2.243187e+06    99.000000    54.000000     2.000000     3.000000  

[8 rows x 26 columns]

In [5]:
df.isnull().sum()

time          0
lread         0
lwrite        0
scall         0
sread         0
swrite        0
fork          0
exec          0
rchar         0
wchar         0
pgout         0
ppgout        0
pgfree        0
pgscan        0
atch          0
pgin          0
ppgin         0
pflt          0
vflt          0
runqsz        0
runocc        0
freemem       0
freeswap      0
usr           0
sys           0
wio         294
idle        294
dtype: int64

In [6]:
x = df[['lread', 'lwrite', 'scall', 'sread', 'swrite']]
y = df['usr']

In [7]:
from sklearn.model_selection import train_test_split as test

x_train, x_test, y_train, y_test = test(x, y, test_size=0.2, random_state=10)

In [8]:
x_test

lread  lwrite  scall  sread  swrite
5079     28       4   5380    351     330
3625      7       0   1703    160     127
1620      3       0   1193    145     152
5827      7       0   1837    262     219
2293     28      18   4804    305     193
...     ...     ...    ...    ...     ...
6386      1       0    864     67      65
4178     19      27   2061     90     106
3405      4       1   1949    222      91
260       1       1   1345    223     192
2063      9       7   4514    197     175

[1639 rows x 5 columns]

In [9]:
y_test

5079    68
3625    78
1620    90
5827    79
2293    78
        ..
6386    97
4178    95
3405    87
260     91
2063    86
Name: usr, Length: 1639, dtype: int64

In [10]:
x_train

lread  lwrite  scall  sread  swrite
4647      8       2   2357    167      99
7793     22      20   1693    167      87
4583     55      47   4025    596     497
5485      6       1   1193     96     236
6211      5       2   1918    140     109
...     ...     ...    ...    ...     ...
1344     34      50   2256    214     159
4623      4       2   2677    248     142
8164      3       1   2860    267     154
7293      1       1    755     72      47
1289     15      11   1875    115      99

[6553 rows x 5 columns]

In [11]:
y_train

4647    89
7793    90
4583    69
5485    92
6211    94
        ..
1344    91
4623    84
8164    90
7293    97
1289    86
Name: usr, Length: 6553, dtype: int64

In [12]:
print(x.shape)
print(y.shape)

print(x_train.shape)
print(y_train.shape)

print(x_test.shape)
print(y_test.shape)

(8192, 5)
(8192,)
(6553, 5)
(6553,)
(1639, 5)
(1639,)


In [13]:
from sklearn.preprocessing import StandardScaler as sc
from sklearn.preprocessing import Normalizer as nm

scaler = sc().fit(x_train)
scaler_x_train = scaler.transform(x_train)
normalized = nm().fit(x_train)
normalized_x_train = normalized.transform(x_train)

scaler = sc().fit(x_test)
scaler_x_test = scaler.transform(x_test)
normalized = nm().fit(x_test)
normalized_x_test = normalized.transform(x_test)

print('Scalar X-train : ', scaler_x_train, '\n')
print('Scalar X-test : ', scaler_x_test, '\n')
print('Normalized X-train : ', scaler_x_train, '\n')
print('Normalized X-test : ', scaler_x_test, '\n')

Scalar X-train :  [[-0.20972794 -0.37189874  0.03470106 -0.21173711 -0.30835604]
 [ 0.0397225   0.24181378 -0.36972745 -0.21173711 -0.38165169]
 [ 0.62771281  1.16238257  1.05064496  1.91923819  2.12261626]
 ...
 [-0.29881738 -0.40599388  0.34106783  0.28499373  0.02758234]
 [-0.33445315 -0.40599388 -0.94104363 -0.68363141 -0.62597052]
 [-0.08500272 -0.06504248 -0.25887506 -0.47003715 -0.30835604]] 

Scalar X-test :  [[ 0.22982466 -0.30918307  1.90576663  0.72447161  1.21070944]
 [-0.29004488 -0.4341063  -0.39288473 -0.28477608 -0.17278919]
 [-0.38906765 -0.4341063  -0.71170774 -0.36403637 -0.00240759]
 ...
 [-0.36431195 -0.40287549 -0.23909952  0.04283312 -0.4181387 ]
 [-0.43857903 -0.40287549 -0.61668598  0.04811714  0.27020298]
 [-0.24053349 -0.21549066  1.36439266 -0.08926737  0.15434349]] 

Normalized X-train :  [[-0.20972794 -0.37189874  0.03470106 -0.21173711 -0.30835604]
 [ 0.0397225   0.24181378 -0.36972745 -0.21173711 -0.38165169]
 [ 0.62771281  1.16238257  1.05064496  1.9192

In [14]:
from sklearn.feature_selection import SelectKBest as best
from sklearn.feature_selection import chi2 as ch

bestFeature = best(score_func=ch, k=3)
fit = bestFeature.fit(x, y)
dfScore = pd.DataFrame(fit.scores_)
dfColumns = pd.DataFrame(x.columns)
featureScores = pd.concat([dfColumns, dfScore], axis=1)
featureScores.columns = ['User', 'Score']
featureScores.nlargest(3, 'Score')

User         Score
2   scall  5.105611e+06
3   sread  5.921482e+05
4  swrite  4.187310e+05

In [15]:
bestFeature = best(score_func=ch, k=3)
fit = bestFeature.fit(x_train, y_train)
dfScore = pd.DataFrame(fit.scores_)
dfColumns = pd.DataFrame(x_train.columns)
featureScores = pd.concat([dfColumns, dfScore], axis=1)
featureScores.columns = ['User', 'Score']
featureScores.nlargest(3, 'Score')

User         Score
2   scall  4.128391e+06
3   sread  4.753949e+05
4  swrite  3.362432e+05

In [16]:
bestFeature = best(score_func=ch, k=3)
fit = bestFeature.fit(x_test, y_test)
dfScore = pd.DataFrame(fit.scores_)
dfColumns = pd.DataFrame(x_test.columns)
featureScores = pd.concat([dfColumns, dfScore], axis=1)
featureScores.columns = ['User', 'Score']
featureScores.nlargest(3, 'Score')

User         Score
2   scall  1.021508e+06
3   sread  1.330183e+05
4  swrite  9.712510e+04